$:.unshift File.dirname(__FILE__)
require 'yajl'
require 'yajl/json_gem'
require 'eventmachine'
require 'em-ssh'
require 'em-synchrony'

require 'souffle/version'
require 'souffle/ssh_monkey'
require 'souffle/log'
require 'souffle/exceptions'
require 'souffle/config'
require 'souffle/state'
require 'souffle/daemon'
require 'souffle/node'
require 'souffle/system'
require 'souffle/provider'
require 'souffle/provisioner'
